### ISSUE TITLE
Emit Telemetry events

### ISSUE THREAD

**Issue by stephanos** [peillis/memcachir#15]
Hello!

[Telemetry](https://github.com/beam-telemetry/telemetry) is getting traction now that it's included in [Phoenix](https://github.com/phoenixframework/phoenix/commit/4d61eacd83d61899a895167715d8754c5c8187be) and [Ecto](https://github.com/elixir-ecto/ecto/commit/ee8a9ea002f8809825d3bd5a3bc34aa863f223ee) out-of-the-box. What's your stance on emitting telemetry events from this library? Would you welcome contributions?

It would allow users of this library to capture important metrics and send them to their monitoring solution. This way, we save everyone the time to instrument their own usage of this library.

Stephan

**Comment by peillis** [comment]
Hi!
Which events do you think should be implemented?

**Comment by stephanos** [comment]
Thank you for getting back to me! Good question!

When I posted this, I had completely forgotten that it relies on `memcachex` under the hood. I think ideally it's their responsibility to track events for the actual Memcache commands. Same with service discovery, that should probably live in `herd` itself.

So ignore me :)

**Comment by stephanos** [comment]
FYI the telemetry update is now in `memcachex`'s latest version `0.5.0`. Would you like me to provide a PR to update its version here?

**Comment by peillis** [comment]
Yes please!

**Comment by stephanos** [comment]
PR is here: https://github.com/peillis/memcachir/pull/16
