### ISSUE TITLE
Memcache connection leak

### ISSUE THREAD

**Issue by michaeljguarino** [peillis/memcachir#8]
We recently upgraded to the latest memcachir version from one of our local forks, and immediately found a connection leak.  I'm not entirely certain of the root cause, but we witnessed monotonic increases in connection counts on our elasticache cluster (eventually terminated when we hit process ulimits).  We're currently running on elixir 1.7.2 in docker (with a distillery release).

My guess is the root cause might be due to some nuance in the supervision of the health check.  Or perhaps the pool isn't tearing down the memcachex connection processes correctly so that they actually close their sockets.

Here's our fork for comparison: https://github.com/Frameio/memcachir

**Comment by peillis** [comment]
you're right. I've detected the same problem. The number of connections keeps steadily growing.
@stephanos could you please take a look at this?

**Comment by stephanos** [comment]
@peillis 👍 I'll have a look

**Comment by stephanos** [comment]
@peillis @michaeljguarino do you have more data? For example, how quickly is the number growing? And how do you track that number?

I looked at our monitoring and can't see any issues there. It's steady and we've seen no crashes whatsoever. Caveat: we're still on our fork.

I've took a look around and so far nothing obvious pops out. I looked at the number of processes, it stays steady. When I kill the ElastiCache connection it drops and then goes back to the same number of processes. So I'll try to look at the underlying connections next.

**Comment by stephanos** [comment]
Following the health check call, you end up with:

 - `Memcachir.Util.get_servers`
 - `Memcachir.Util.read_config_elasticache`
 - `Elasticachex.get_cluster_info`
 - `Elasticachex.Socket.connect`
   - `Socket.TCP.connect`
 - `Elasticachex.Socket.send_and_recv`
   - `Socket.Stream.send!` and `Socket.Stream.recv`

I can't be sure, but my money is on `Elasticachex` not closing the connection. I suppose `Elasticachex` was never built to be called multiple times and just doesn't bother with closing the socket. But now that it's called regularly, that becomes a problem.

**Comment by michaeljguarino** [comment]
It's a very linear rate, so the elasticachex connection might be the culprit as it happens once per poll interval.  I can try to look up the graphs from last week if it will help.

**Comment by michaeljguarino** [comment]
The one thing about that though, is my understanding was that elasticachex uses elasticache's discovery endpoint, which shouldn't connect to individual nodes (we were seeing connection increases to each node in the cluster)

**Comment by stephanos** [comment]
Hm, yes, that's true. The health check endpoint should not lead to an increase in connections to individual nodes. If you could double-check where the increase of connections happens exactly, that would be helpful IMHO.

It could be possible that once a node addition/removal happens and the supervision tree restarts, that connections are leaking. But to see a significant, steady increase like you are describing, that event would have to happen _all the time_. In our systems, I observed that happening maybe 1-2 per month, tops. So I'm still thinking it's the health check.

**Comment by michaeljguarino** [comment]
The connections are definitely to individual nodes.  Here's a graph:

<img width="927" alt="screen shot 2018-08-12 at 1 31 24 pm" src="https://user-images.githubusercontent.com/3838088/44004687-78739904-9e34-11e8-8281-3ca6e80f17ae.png">

The rate is very linear and rarely interrupted, maybe increasing 10-20 per minute or so.  It's almost like the connection pools are becoming detached from the supervision tree (because it's about the pool size) and not reclaimed or something.

**Comment by stephanos** [comment]
Ah, thank you. I've looked at the application metrics before; I can see the same pattern in our AWS metrics now. 🤔

**Comment by michaeljguarino** [comment]
I have a branch with some improvements to the cluster management stuff I've been working on that might help with some of this. I can create a pr and we can work off of that.

**Comment by peillis** [comment]
The thing I observed it's an increase of 1 connection every minute or so. I was checking with netstat the number of connections.

**Comment by stephanos** [comment]
@peillis interesting. that would indicate the health check is responsible (it opens exactly 1 connection every minute). Mind trying to update `elasticachex` and close that TCP connection (I think it's `@socket |> Socket.Stream.close`)?

**Comment by michaeljguarino** [comment]
That's definitely possible.  Us seeing 10 connections a minute could just be due to us having ~10 nodes in our service (all making healthchecks).

**Comment by michaeljguarino** [comment]
@peillis I went ahead and opened a PR that should handle closing the TCP connection on elasticachex if you want to take a look

**Comment by peillis** [comment]
Ok, I've checked with your PR and works perfect. I'll make a new release with your other PR and updating elasticachex as soon as I can.
Thank you very much to both for your work.

**Comment by michaeljguarino** [comment]
No worries, it was a fun problem to solve

**Comment by michaeljguarino** [comment]
Also, if you don't mind, I think I might move the clustering behavior into it's own repo so it could be reused for similar problems (like clustering redis, etcd or whatever).  Basically a set of macros for generating a cluster manager and the supervisor for the pool and cluster.

**Comment by peillis** [comment]
Sure, no problem. Then I'll make a release with just a new elasticachex version.

**Comment by michaeljguarino** [comment]
I probably won't get to that for a while, but if you'd rather just rev elasticachex no worries.  That's the more immediate concern.

**Comment by stephanos** [comment]
@michaeljguarino just curious, did that fix actually solve the leaking connection problem for you? I still see growing connections in CloudWatch.

**Comment by michaeljguarino** [comment]
That's weird, we're totally fine.
